### PR TITLE
Fixes #6 Add individual commands

### LINKED ISSUE #6: Go get fails with a redeclaration error
```
$ go get ./...
```

Fails with:

    # github.com/LibreRead/server
    ./server.go:63: main redeclared in this block
           previous declaration at ./quote.go:26

Haven't looked further, but this is likely as part of a testing strategy to test quote in isolation, but why not make `cmd/quote/main.go` and `cmd/server/main.go` to handle using the rest as a library.

### PR DESCRIPTION
**Pull request by gbraad**
```
$ go get ./...
$ go install -v ./cmd/server
$ go install -v ./cmd/quote
```

you can however still use:
```
$ go build -o server ./cmd/server
```

but had to remove the entries for `quote` and `server` from `.gitignore`.

### CODE REVIEW

**Comment by mysticmode** [comment]
No, binaries shouldn't be in the development repo.

**Comment by mysticmode** [comment]
I'll move this to dev branch and work on it. Thanks for the idea!

**Comment by gbraad** [comment]
@mysticmode binaries should never end up in the root of the repo, this is why `go install` is a better idea, or at least do a `go build -o out/server ./cmd/server`. In that case you do not have to .gitignore a very general term like `quote` or `server`, but instead `out/`

**Comment by kpcyrd** [comment]
It seems this was reverted. Are there any instructions on how to build this? As far as I know having multiple definitions of main in the project root is considered worse than having a binary that is excluded by .gitignore. This project is currently not `go install`-able, so I'd like to reopen #6.

**Comment by gbraad** [comment]
@kpcyrd I can't reopen #6

**Comment by mysticmode** [comment]
@kpcyrd Currently, I'm working on the developer documentation.

`quote.go` doesn't have any relation with LibreRead code. It's just a microservice where I'll pulll the quotation.

Shall I put the quote.go in a separate repo for now?

**Comment by gbraad** [comment]
@mysticmode quote or not, having a `cmd/server` is cleaner in approach, as this will make the root acts as a library, nice for re-use... and it allows the binary also to be treated as an installable.

**Comment by mysticmode** [comment]
As @gbraad suggested, I have added individual commands.

@gbraad Could you check and let me know if that is fine?

**Comment by kpcyrd** [comment]
I'm able to build the project using the following dockerfile:

```
FROM golang
WORKDIR /go/src/github.com/LibreRead/server
COPY . .
RUN rm quote.go # workaround
RUN go-wrapper download
RUN go-wrapper install ./cmd/server/
EXPOSE 8080
ENTRYPOINT ["server"]
```

I had to remove quote.go from the project root due to this error:
```
+ exec go get -v -d
can't load package: package github.com/LibreRead/server: found packages quote (quote.go) and libreread (server.go) in /go/src/github.com/LibreRead/server
```

If we can get this resolved I'm going to PR my docker file and would work on a docker-compose setup next.

Personally I'd prefer if the binary could be renamed from `server` to `libreread` or `libreread-server` to avoid that somebody actually installs a `server` binary to their system.

**Comment by mysticmode** [comment]
@kpcyrd Thank you, I'll put the quotation code in a separate repo. And that's a good suggestion to change the binary name. I'll do that now.

**Comment by kpcyrd** [comment]
You can keep the file in this repo, you only have to change the package name in `/quote.go` from `quote` to `libreread` to fix the build. I think it might make sense to have it as a module that is compiled into libreread instead of having two processes in the first place. :)

**Comment by mysticmode** [comment]
No, I have plans to enhance the quotation code and I think it would be better if I put in a separate repo as this is not something related to the server.

**Comment by mysticmode** [comment]
@gbraad @kpcyrd is it ok for you guys to come to the chat room now? It would be easier for me to communicate to clear this issue.
https://discord.gg/wHCM7DZ

I have few other things to do for the demo site, which is a priority now.

**Comment by gbraad** [comment]
@mysticmode I am OK with the change, but in future... since you deal with an Open Source license, please have the attribution intact, or add to it. Just a gentle reminder...

**Comment by gbraad** [comment]
the change that is included now, would not cause the issue that @kpcyrd talks about. I am OK with how quote lives now... anyways, you can find me on Freenode as gbraad. I mostly reside in the #fedora, #openshift, chatrooms

**Comment by mysticmode** [comment]
I moved the quotation code to this repo https://github.com/LibreRead/quote

@gbraad Please close this issue if you are fine with the changes. Thanks!

**Pull request merged**
